version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6380"
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    ports:
      - "1182:1182"