version: '3'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    ports:
      - "1182:1182"