server:
  port: ${APP_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: "10MB"
  config:
    import: "optional:file:env.properties"
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://hindev9th:b4SvMam66Q5ZWRfs@cluster0.qavd2co.mongodb.net/comics-app}
      authentication-database: ${AUTHENTICATION_DB:admin}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
