server:
  port: ${APP_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: "10MB"
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_URI}
      authentication-database: ${AUTHENTICATION_DB:admin}
      auto-index-creation: true