server:
  port: ${APP_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: "10MB"
  config:
    import: "optional:file:env.properties"
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/test}
      authentication-database: ${AUTHENTICATION_DB:admin}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
